EmprestimoLivros/Models/EmprestimosModel.cs
using System.ComponentModel.DataAnnotations;

namespace EmprestimoLivros.Models
{
    public class EmprestimosModel
    {
        public int Id { get; set; }

        [Required(ErrorMessage ="Campo obrigatório")]
        public string Recebedor { get; set; }

        [Required(ErrorMessage = "Campo obrigatório")]
        public string Fornecedor { get; set; }

        [Required(ErrorMessage = "Campo obrigatório")]
        public string LivroEmprestado { get; set; }

        public DateTime dataUltimaAtualizacao { get; set; } = DateTime.Now;

    }
}

EmprestimoLivros/Models/ErrorViewModel.cs
namespace EmprestimoLivros.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

EmprestimoLivros/Controllers/EmprestimoController.cs
using EmprestimoLivros.Data;
using EmprestimoLivros.Models;
using Microsoft.AspNetCore.Mvc;

namespace EmprestimoLivros.Controllers
{
    public class EmprestimoController : Controller
    {

        readonly private ApplicationDbContext _db;
        public EmprestimoController(ApplicationDbContext db)
        {
            _db = db;
        }
        public IActionResult Index()
        {
            IEnumerable<EmprestimosModel> emprestimos = _db.Emprestimos;
            return View(emprestimos);
        }

        public IActionResult Cadastrar()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Cadastrar(EmprestimosModel emprestimos)
        {
            if (ModelState.IsValid)
            {
                _db.Emprestimos.Add(emprestimos);
                _db.SaveChanges();

                return RedirectToAction("Index");
            }

            return View();
        }
    }
}

EmprestimoLivros/Controllers/HomeController.cs
using EmprestimoLivros.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace EmprestimoLivros.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

EmprestimoLivros/Views/Emprestimo/Cadastrar.cshtml
@model EmprestimosModel
@{
    ViewData["title"] = "Cadastrar Empréstimo";
}

<div class="container bg-dark p-5 rounded-5">
    <div class="mb-5 text-center">
        <h1 class="text-light">Cadastro De Empréstimos</h1>

    </div>

<form method="post" asp-controller="Emprestimo" asp-action="Cadastrar">


    <div class="mb-3">
            <label for="Recebedor" class="form-label text-light">Recebedor:</label>
            <input type="text" class="form-control text-light" asp-for="Recebedor" id="Recebedor" placeholder="Quem está recebendo o livro?">
    <span class=text-danger asp-validation-for="Recebedor"> </span>
        </div>


    <div class="mb-3">
            <label for="Fornecedor" class="form-label text-light">Fornecedor:</label>
            <input type="text" class="form-control text-light" asp-for="Fornecedor" id="Fornecedor" placeholder="Quem está emprestando o livro?">
            <span class=text-danger asp-validation-for="Fornecedor"> </span>

        </div>


    <div class="mb-3">
        <label for="Livro" class="form-label text-light">Livro:</label>
            <input type="text" class="form-control text-light" asp-for="LivroEmprestado" id="Livro" placeholder="Título do livro que está sendo emprestado.">
            <span class=text-danger asp-validation-for="LivroEmprestado"> </span>

        </div>



    <div class="d-flex gap-5 mt-5">
        <button type="submit" class="btn btn-success w-50">Adicionar</button>
        <a class="btn btn-primary w-50 " asp-controller="Emprestimo" asp-action="Index">Voltar</a>
    </div>





</form>
</div>

EmprestimoLivros/Views/Emprestimo/Index.cshtml
@model IEnumerable<EmprestimosModel> 

<div class="container">
    <div class="d-flex justify-content-between align-items-center mb-5">
        <h1>Empréstimos</h1>
        <a class="btn btn-success mx-2" asp-controller="Emprestimo" asp-action="Cadastrar">Cadastrar novo empréstimo</a>
    </div>

<table class="table table-dark table-hover">
    <thead>
        <tr>
            <th scope="col">Recebedor</th>
            <th scope="col">Fornecedor</th>
            <th scope="col">Livro</th>
            <th scope="col">Data do Empréstimo</th>
        </tr>
    </thead>
    <tbody>


        @if (Model != null)
        {
            @foreach (var emprestimo in Model)
            {
                <tr>
                    <th scope="row">@emprestimo.Recebedor</th>
                    <td>@emprestimo.Fornecedor</td>
                    <td>@emprestimo.LivroEmprestado</td>
                    <td>@emprestimo.dataUltimaAtualizacao</td>
                </tr>
            }

        }

       
    </tbody>
</table>

</div>

EmprestimoLivros/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">

    <h1 class="display-4">Empréstimos Online</h1>
    <p>Abra um livro, deixe-se levar.</p>
    <img src="/img/book.png"
</div>

EmprestimoLivros/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Livraria Tech</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/materiatheme.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/EmprestimoLivros.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-dark border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand text-light" asp-area="" asp-controller="Home" asp-action="Index"><i class="bi bi-book mx-2"></i>Livraria Tech</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="Index"><i class="bi bi-house-fill mx-2"></i>Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Emprestimo" asp-action="Index"><i class="bi bi-collection mx-2"></i>Empréstimos</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>